### ISSUE TITLE
Move still possible with no rights

### ISSUE THREAD

**Issue by Tazzios** [JoomGalleryfriends/JoomGallery#62]
**Situation**
set access to 'edit own'
In the backend the status buttons and the link to the edit page are not clickable if the image is not yours.

-If you select the image using the checkbox and press delete you get the warning: 
_You are not allowed to delete one of the selected images_

-If you try the batch option you only have an close option.
So these 2  ar OK. 

**Problem**
-But if you click on the move button you can move the image to an other category. 

**Solution**
The save and close button should also be not present just like the batch option

environment
Gallery 3.4.1 J3.9.22

**Comment by MrMusic** [comment]
>**Problem**
>-But if you click on the move button you can move the image to an other category.

I tried to understand the problem.
If I try to move a single image with the 'Move' button, although I have no authorization (only 'Edit Own' is Allowed) an error message appears:
**Notice
You are not allowed to move one of the listed images to the selected category**
and the image remains in the category.
Maybe your owner belongs to a user group that has further permissions ('Edit' is Allowed)?

**Comment by Tazzios** [comment]
I recreated it in a test enviroment (Gallery 3.5.0 J3.9.23) and recorded it. I can also give you access if you want to check authorization.

Move is possible: What you see, I move the image which i cannot edit to a folder that I am allowed to edit after that i also van edit the image.
![joomgallery move](https://user-images.githubusercontent.com/23451105/104006630-075f3380-51a7-11eb-896e-59525b77d21b.gif)

Batch option is not possible at the file: What you see, i trie to a batch edit on the file but i do not have a save button, which is correct behavior.
![joomgallery batch](https://user-images.githubusercontent.com/23451105/104006990-89e7f300-51a7-11eb-91e3-0a6ad5103bcb.gif)

**Comment by MrMusic** [comment]
I would like to see how the permissions of the image (Fun) are set and to which user group(s) the user belongs.
It would be nice if you could give me access to the site, then I would take a look.

**Comment by Tazzios** [comment]
will put it temporally here because i do not see an private option:

https://www.famrodenburg.net/test/
test account: joomgallery joomgallery
admin account:  admin joomgallery

let me know if you have copied it then i will remove the logins from this message.

**Comment by MrMusic** [comment]
>will put it temporally here because i do not see an private option:

You can send me via forum personal message / conversation 
or email, see imprint at website.

**Comment by MrMusic** [comment]
@Tazzios
Some time ago i sent you a possible fix in the JoomGallery forum. 
Does it work for you?

**Comment by Tazzios** [comment]
@MrMusic sorry i did not see that yet( i now turned the Conversations notifications on).
I will test it this weekend and place my findings here.

**Comment by Tazzios** [comment]
almost weekend. ;)

testresults
scenario1: select 2 image with and without access.
result: only the image with access is moved

scenario2: select image one without access.
result: no image is moved.

So technically it is working tough for GUI it would be nice if in scenario2 the save button would not be available (like with the batch). Currently there is no feedback that the move didn't take place.

new (similar) finding is that the permissions check is also missing on the recreate and rotate buttons.

**Comment by MrMusic** [comment]
>almost weekend. ;)

Nice for you :-)

>...it would be nice if in scenario2 the save button would not be available

Since images from different categories can be selected in the image manager, it must be checked for each image separately whether the authorization is available.
I imagine it to be quite difficult to check this even before starting the function.

>...(like with the batch)

Batch processing also only carries out the check for each image separately when the (Save) function is started.
You might mean the edit form that appears when you click 'Batch' but only one image has been selected? ->Then appears the single image form.

>Currently there is no feedback that the move didn't take place

If an image cannot be moved, a Notice appears like:
Notice
You are not allowed to move xx of the listed images to the selected category

**Comment by Tazzios** [comment]
I now noticed that the batch opens the normal edit screen when only one image is selected. That explains why the save button is not available. When select multiple it uses the batch which behaves the same as move.

Your correct that it indeed does show an 'notice', only i didn`t notice.
For comparison if something is not possible with the batch the messages is shown as an error, with missing translation (maybe my install).
error
COM_JOOMGALLERY_COMMON_MSG_NOT_ALLOWED_TO_EDIT_IMAGE 

Maybe show the moves also as an error for consistency?

Did you also checked my additional the recreate and rotate buttons comment.

**Comment by MrMusic** [comment]
I started a Pull Request to fix the problem: https://github.com/JoomGalleryfriends/JoomGallery/pull/66
Perhaps there will then be further tests and tips.

>...with missing translation...

There is a missing language constant in the language file. I fixed that too.

>Maybe show the moves also as an error for consistency?

I think a notice or a warning would be the right thing to do?
It should appear as an error if you have the authorization, but it still does not work due to an error.

>Did you also checked my additional the recreate and rotate buttons comment.

Yes, but I don't know what the right way to fix this problem.
I'm waiting for suggestions from the community.
Maybe the recreate and rotate buttons should only be visible to a right 'administrator'?
